language: node_js

branches:
  only:
    - develop
    - travis

matrix:
  include:

    # WINDOWS cross-built from linux
    - os: linux
      dist: trusty
      sudo: required
      env:
          - DISPLAY=:99.0
      node_js: 6
      cache:
        yarn: true
      addons:
        apt:
          packages:
          - icnsutils
          - graphicsmagick
          - xz-utils
      before_install:
        - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
        - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
        - sudo apt-get update -q
        - sudo apt-get install --no-install-recommends -y wine1.8 mono-devel ca-certificates-mono
      before_script:
        - "export PATH=$HOME/.meteor:$PATH"
        - sh -e /etc/init.d/xvfb start
      script:
        - gulp mist --platform win

    # LINUX
    - os: linux
      dist: trusty
      sudo: required
      node_js: 6
      cache:
        yarn: true
      addons:
        apt:
          packages:
          - gcc-multilib
          - g++-multilib
      before_script:
        - "export PATH=$HOME/.meteor:$PATH"
        - sh -e /etc/init.d/xvfb start
      script:
        - gulp mist --platform linux

    # MAC
    - os: osx
      osx_image: xcode7.3
      node_js: 6
      cache:
        yarn: true
      before_script:
        - "export PATH=$HOME/.meteor:$PATH"
      script:
        - gulp mist --platform mac

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
  - npm install -g meteor-build-client
  - npm install -g electron@1.3.5
  - yarn

after_success:
  - gulp mist-checksums


# notifications:
#   webhooks:
#     urls:
#       - YOUR_WEBHOOK_URL
#     on_success: change
#     on_failure: always
#     on_start: never
