language: node_js

matrix:
  include:
    - os: linux
      sudo: true
      dist: trusty
      node_js: 6
      before_install:
      - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
      - sudo apt-get update -q
      - sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick gcc-multilib g++-multilib wine1.8 xz-utils
      script:
        - gulp --platform linux, win
    - os: osx
      osx_image: xcode8.1
      node_js: 6
      script:
        - gulp --platform mac

before_script:
  - curl https://install.meteor.com/ | sh
  - PATH=$PATH:~/.meteor
  - npm install -g meteor-build-client
