language: node_js
sudo: false
matrix:
  include:
    - os: linux
      dist: precise
      node_js: 6
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
            - xz-utils
            - gcc-multilib
            - g++-multilib
      script:
        - gulp --platform linux
    - os: osx
      osx_image: xcode8.1
      node_js: 6
      script:
        - gulp --platform mac

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl https://install.meteor.com/ | sh
  - PATH=$PATH:~/.meteor
  - npm install -g meteor-build-client
