language: node_js

branches:
  only:
    - develop
    - travis

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
          - DISPLAY=:99.0
      node_js: 6
      cache:
        yarn: true
      addons:
        apt:
          packages:
          - icnsutils
          - graphicsmagick
          - xz-utils
          - gcc-multilib
          - g++-multilib
      install:
        - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
        - npm install -g meteor-build-client
        - npm install -g electron@1.3.5
      before_script:
        - "export PATH=$HOME/.meteor:$PATH"
        - yarn
      script:
        - sh -e /etc/init.d/xvfb start
        - npm run ci

# notifications:
#   webhooks:
#     urls:
#       - YOUR_WEBHOOK_URL
#     on_success: change
#     on_failure: always
#     on_start: never
