language: node_js
sudo: required

branches:
  only:
    - develop
    - travis

matrix:
  include:

    # WINDOWS cross-built from linux
    - os: linux
      dist: trusty
      env:
          - GULP_PLATFORM=win
          - DISPLAY=:99.0
      node_js: 6
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
            - xz-utils
            - gcc-multilib
            - g++-multilib
          sources:
            - mono
      before_install:
        - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
        - sudo dpkg --add-architecture i386
        - sudo apt-get update -q
        - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono
        - sudo apt-get install --no-install-recommends -y wine1.8
      before_script:
        - sh -e /etc/init.d/xvfb start

    # LINUX
    - os: linux
      dist: trusty
      env:
          - GULP_PLATFORM=linux
      node_js: 6
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
            - xz-utils
            - gcc-multilib
            - g++-multilib

    # MAC
    - os: osx
      osx_image: xcode7.3
      env:
          - GULP_PLATFORM=mac
      node_js: 6
      before_install:
        - brew update
        - brew install gnu-tar libicns graphicsmagick xz

cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
  - "export PATH=$HOME/.meteor:$PATH"
  - npm install -g meteor-build-client
  - npm install -g electron@1.3.5
  - yarn

script:
  - travis_wait 30 gulp mist --platform $GULP_PLATFORM

after_success:
  - gulp mist-checksums

# notifications:
#   webhooks:
#     urls:
#       - https://webhooks.gitter.im/e/33972d9e627a142c57a6
#     on_success: change
#     on_failure: always
#     on_start: never
