language: node_js
node_js: 6

cache:
  yarn: true

matrix:
  include:
    - os: linux
      sudo: false
      dist: precise
      addons:
        apt:
          packages:
          - icnsutils
          - graphicsmagick
          - xz-utils
          - gcc-multilib
          - g++-multilib

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl https://install.meteor.com/ | sh
  - PATH=$PATH:~/.meteor
  - npm install -g meteor-build-client

script:
  - gulp --platform linux
