language: node_js
node_js: 6

branches:
  only:
    - develop
    - travis

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
          - DISPLAY=:99.0
      cache:
        yarn: true
      addons:
        apt:
          packages:
          - icnsutils
          - graphicsmagick
          - xz-utils
          - gcc-multilib
          - g++-multilib
      before_script:
        - sh -e /etc/init.d/xvfb start
      before_install:
        - curl https://install.meteor.com/ | sh

install:
  - npm install -g meteor-build-client

script:
  - npm run ci

# notifications:
#   webhooks:
#     urls:
#       - YOUR_WEBHOOK_URL
#     on_success: change
#     on_failure: always
#     on_start: never
