language: node_js

cache:
  yarn: true

matrix:
  include:
    - os: linux  ## build linux and win in one run; installation of wine is considerable faster using apt than brew on osx
      sudo: required
      dist: trusty
      node_js: 6
      before_install:
      - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF  ## dep for win: add mono
      - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
      - sudo add-apt-repository ppa:ubuntu-wine/ppa -y  ## dep for win: add wine1.8
      - sudo dpkg --add-architecture i386  ## dep for win: add i386 for wine installation
      - sudo apt-get update -q
      - sudo apt-get install --no-install-recommends -y ca-certificates-mono icnsutils graphicsmagick gcc-multilib g++-multilib mono-devel wine1.8 xz-utils
      script:
        - gulp --platform linux,win
    - os: osx
      osx_image: xcode8.1
      node_js: 6
      script:
        - gulp --platform mac

before_script:
  - curl https://install.meteor.com/ | sh
  - npm install -g meteor-build-client gulp
