language: node_js
sudo: required

branches:
  only:
    - develop
    - travis

matrix:
  include:

    # WINDOWS cross-built from linux
    - os: linux
      dist: trusty
      env:
          - GULP_PLATFORM=win
          - DISPLAY=:99.0
      node_js: 6
      addons:
        apt:
          packages:
          - icnsutils
          - graphicsmagick
          - xz-utils
          - mono
      before_install:
        - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
        # - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        # - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
        - sudo apt-get update -q
        # - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono
        - sudo apt-get install --no-install-recommends -y wine1.8
      before_script:
        - sh -e /etc/init.d/xvfb start

    # LINUX
    - os: linux
      dist: trusty
      env:
          - GULP_PLATFORM=linux
      node_js: 6
      addons:
        apt:
          packages:
          - icnsutils
          - gcc-multilib
          - g++-multilib

    # # MAC
    # - os: osx
    #   osx_image: xcode7.3
    #   env:
    #       - GULP_PLATFORM=mac
    #   node_js: 6

cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
  - "export PATH=$HOME/.meteor:$PATH"
  - npm install -g meteor-build-client
  - npm install -g electron@1.3.5
  - yarn

script:
  - gulp mist --platform $GULP_PLATFORM

after_success:
  - gulp mist-checksums


# notifications:
#   webhooks:
#     urls:
#       - YOUR_WEBHOOK_URL
#     on_success: change
#     on_failure: always
#     on_start: never
