env:  # don't warn about no-def meteor keywords
  meteor: true

rules:
  no-undef: off
  no-var: off
  prefer-arrow-callback: off
  prefer-template: off
  dot-notation: off
  no-underscore-dangle:
    - error
    - allow: ['_id', '_escape', '__']

globals:
  Helpers: true
  Blaze: true
  EthAccounts: true
  mist: true
